### ISSUE TITLE
UITableViewController's tableView doesn't scroll while on SwipeableTabBarController

### ISSUE THREAD

**Issue by dharxx** [marcosgriselli/SwipeableTabBarController#1]
Cannot scroll tableView of UITableViewController after implement SwipeableTabBarController
SwipeableTabBarController
      -> UINavigationController -> UITableViewController1
      -> UINavigationController -> UITableViewController2
Swipe is work but cant scroll tableView

**Comment by dharxx** [comment]
Only happen with UITableViewController not UITableView in UIViewController

**Comment by marcosgriselli** [comment]
Fixed on 1d137a7. Added new tag `1.0.3`
