### ISSUE TITLE
Bug On sideBySide style

### ISSUE THREAD

**Issue by Enricoza** [marcosgriselli/SwipeableTabBarController#10]
Not sure if this is only me, but maybe it helps:

When you drag to the middle of the next view and than you lift your finger, it should end the pan gesture and actually it does, but sometimes (you have to find the right spot) it does the "backing" animation twice (and the second one comes with a black background cause i think the other VC is not there anymore)

Oddly enough it happens only in some VC and only on my iPhone 6s, not on simulator...

I repeat, maybe is a problem i created in my own project and i will look into it, but if it's not maybe you want to fix it :)
Hope it helps
Bye

**Comment by Enricoza** [comment]
If you enable diagonal swipe it is even worse, but i don't know if maybe it's because i am in a vertically scrollable collection view in the meanwhile

**Comment by marcosgriselli** [comment]
@Enricoza I'll look into it, if you find anything else that can be helpful post it

**Comment by supermnemonic** [comment]
i experienced it too. my solution is to edit SwipeAnimation.swift inside animateTransition() then inside completion block of UIView.animate(), to be like this.
```
DispatchQueue.main.asyncAfter(deadline: .now() + 0.1, execute: {
                            self.animationStarted = false
                            if transitionContext.transitionWasCancelled {
                                toView?.removeFromSuperview()
                            } else {
                                fromView?.removeFromSuperview()
                            }
                            transitionContext.completeTransition(!transitionContext.transitionWasCancelled)
                        })
```

**Comment by marcosgriselli** [comment]
@supermnemonic wanna send a PR? I'm currently traveling and will be able to review/test it in a few days.
