### ISSUE TITLE
Compile issue

### ISSUE THREAD

**Issue by borut-t** [marcosgriselli/SwipeableTabBarController#102]
Can you please prepare a new release from master since the latest 3.3.0 version doesn't include an updated package file. Therefore the project cannot be compiled.

**Comment by marcosgriselli** [comment]
@borut-t thanks for reporting! I just created a new release [3.3.1](https://github.com/marcosgriselli/SwipeableTabBarController/releases/tag/3.3.1) with the updated `Package.swift` file
