### ISSUE TITLE
Flickering  when starts swiping

### ISSUE THREAD

**Issue by borut-t** [marcosgriselli/SwipeableTabBarController#104]
This doesn't happen all the time, but it's quite easy to reproduce. Just swipe slowly between pages/tabs and you'll notice flickering when swipe starts. It looks like smth is fighting between each other to get the correct position. I didn't test other transition types, but it's happening for `sideBySide` transition to me.

**Comment by marcosgriselli** [comment]
@borut-t can you upload a video of the issue? Just so we can use it as a reference.

**Comment by borut-t** [comment]
@marcosgriselli I've just tested with the default transition animator and it works. Looks like my custom animation has issues. Sorry for the trouble.

**Comment by borut-t** [comment]
Actually, the problem persists and has nothing to do with the animator. You can check this out by changing line 61 in `SwipeTransitionAnimator`:

```swift
let animator = UIViewPropertyAnimator(duration: duration, curve: .linear, animations: {
  self.animationType.animation(fromView: fromView, toView: toView, direction: fromRight)
})
```
to
```swift
let animator = UIViewPropertyAnimator(duration: duration, dampingRatio: 0.8) {
  self.animationType.animation(fromView: fromView, toView: toView, direction: fromRight)
}
```

So I'm using spring animation instead, and that flickering becomes obvious.

**Comment by borut-t** [comment]
I think this issue comes from the fact that you ignore the "began" phase of gesture recognizer.

**Comment by marcosgriselli** [comment]
@borut-t thanks for reporting this. I can't really explain why it only happens when using a spring animation but the bug happens when we add the `toView` to the transition container. The `toView` is shown for a split second when is added to the stack but not yet placed correctly. 

Since side by side views never overlap we can change the order in the `addTo(container...` method for side by side: 

```swift 
public func addTo(containerView: UIView, fromView: UIView, toView: UIView) {
    switch self {
    case .push, .sideBySide:
        containerView.insertSubview(toView, belowSubview: fromView)
    default:
        containerView.addSubview(toView)
    }
}
```

I just tested this and it works as expected. Can you try it out and let me know if it works for your use case? I'll send a PR after confirmation.

**Comment by borut-t** [comment]
Thanks, @marcosgriselli. I don't have much time to play around with this but I've tried setting `toView.isHidden = true` before calling `addTo` and `toView.isHidden = false` after calling `prepare`. And it's also covered. 
If you were able to fix and test this flickering with your fix, please prepare a PR.

**Comment by borut-t** [comment]
@marcosgriselli hey! Is there any progress on that?

**Comment by marcosgriselli** [comment]
@borut-t done! Check out version 3.4.1
