### ISSUE TITLE
Can't Update with Carthage

### ISSUE THREAD

**Issue by aiartsev** [marcosgriselli/SwipeableTabBarController#106]
Your issue may already be reported!
Please search on the [issue track](https://github.com/marcosgriselli/SwipeableTabBarController/issues?utf8=✓&q=) before creating one.

## Expected Behavior
Being able to update with carthage using `carthage update --platform iOS`

## Current Behavior
As of versioon 3.3.1 onwards, I'm getting the error
`Dependency "SwipeableTabBarController" has no shared framework schemes for any of the platforms: iOS`

## Possible Solution
It works fine making a rollback to 3.3.0.

## Steps to Reproduce (for bugs)
Include in cartfile:
`github "marcosgriselli/SwipeableTabBarController"`
Run `carthage update --platform iOS`

## Environment
* SwipeableTabBarController version: 3.3.1, 3.4.0, 3.4.1

**Comment by marcosgriselli** [comment]
@aiartsev thanks for reporting this. I changed the project structure to follow a more Swift Package Manager like approach and broke Carthage support by accident.. I'll review possible solutions and send a fix tomorrow.

**Comment by marcosgriselli** [comment]
@aiartsev this should be fixed now `carthage update --platform iOS --use-xcframeworks` should work correctly.
