### ISSUE TITLE
How can I `setTabBarSwipe(enabled: false)`

### ISSUE THREAD

**Issue by Desgard** [marcosgriselli/SwipeableTabBarController#11]
I didn't want to get the feature, which is **swiping the controller to change the controller**.
And where will I add the `setTabBarSwipe(enabled: false)` code to forbidden this feature. 😭

**Comment by marcosgriselli** [comment]
Just call `setTabBarSwipe(enabled: false)` on the ViewController's `viewDidLoad()` method.

**Comment by Desgard** [comment]
@marcosgriselli Thx for your reply.

How need I to do something else?

![2017-04-19 8 13 54](https://cloud.githubusercontent.com/assets/7804535/25158063/35e2a9e4-24d8-11e7-8590-71a68cf0581c.png)

**Comment by marcosgriselli** [comment]
Probably `import SwipeableTabBarController` on your `UIViewController` subclass

**Comment by Desgard** [comment]
When I update `1.0.4` from `1.0.0` , I solve it.
I'm so foolish.... 😭
Thx a lot.
