### ISSUE TITLE
this code is available in Objective C?

### ISSUE THREAD

**Issue by kuldeep13990** [marcosgriselli/SwipeableTabBarController#12]
i am not familiar with Bridging code so can you tell me that this code is available in Objective C?

or can you guide me how can i use this in Objective C?

**Comment by marcosgriselli** [comment]
Hi @kuldeep13990 , you **can** use `SwipeableTabBarController` on Objective-C. Check this [StackOverflow answer](http://stackoverflow.com/questions/24102104/how-to-import-swift-code-to-objective-c) for how to bridge Swift code into your Objective-C app.
