### ISSUE TITLE
One View is Overlap on Another View and App Stucked

### ISSUE THREAD

**Issue by kuldeep13990** [marcosgriselli/SwipeableTabBarController#13]
I have 3 ViewControllers in TabBar, 1st is TableView, 2nd is Video Recording Screen and 3rd is Tableview.

i am hiding TabBar in 2nd Screen.
When i swipe from 3rd Tab to 2nd Tab, on top there's 3rd Tableview screen display in device but when i view it by **"Debug view hierarchy"** , actually 2nd Video Recording screen is on the top and app Stucked.

i also try to replace simple view controller on 2nd screen, it works fine.

this issue occurs of hiding and showing TabBar?

any help will be helpful thanks.

**Comment by marcosgriselli** [comment]
@kuldeep13990 sorry for the delay. Yes, the issue is related to hiding the tabBar, so far this library doesn't support this type of functionality but I'll take it into consideration in the future.
