### ISSUE TITLE
Disable animation for tab bar button

### ISSUE THREAD

**Issue by KoD4K** [marcosgriselli/SwipeableTabBarController#15]
Is it possible temporary disable animation when user press button in tab bar? 

I know how to stop swipe but I also need to disable animation sometimes.

Additional: is it possible to change animation? When user press button in tab bar I need to have sideBySide animation but when I want to change selected index programmatically I need push animation.

Thanx a lot!

**Comment by marcosgriselli** [comment]
Disabling animation seems an easy addition, I'll work on it over the week. 

To change the animation use `setSwipeAnimation(type: SwipeAnimationType.sideBySide)` or whatever animation type you want previous to the action.

**Comment by KoD4K** [comment]
I'm really sorry but when 1.0.5 version is comming? I'm really need function to disable animation. Is it possible to added before you adapt to swift 4.0? 
Thanx a lot for your answer!

**Comment by marcosgriselli** [comment]
b916eaa Added support for disabling animation on item tap. 

Use it like this: 
```swift 
func tabBarController(_ tabBarController: UITabBarController, shouldSelect viewController: UIViewController) -> Bool {
        let shouldAnimate = viewController != viewControllers?[1]
        setAnimation(enabled: shouldAnimate)
        return true
    }
```
