### ISSUE TITLE
delay completing animation when lift finger (touch ended / pan ended)

### ISSUE THREAD

**Issue by supermnemonic** [marcosgriselli/SwipeableTabBarController#16]
so I implemented sideBySide animation. i tried to swipe it fast, but when I immediately lift my finger, there is some delay so that handle-pan state ".ended" is called after a moment, and result is the completing animation is delayed. can somebody give solution ???

**Comment by marcosgriselli** [comment]
Is there a delay just on the .ended case? Or is it on the entire `handlePan(_ recognizer: UIPanGestureRecognizer)` function? 

I'm trying to swipe as fast as I can and don't get any significant delay on the .ended case:

<img width="610" alt="screen shot 2017-07-24 at 7 29 43 pm" src="https://user-images.githubusercontent.com/14804033/28536027-b04fc044-70a6-11e7-9a26-cdb202bb7b69.png">

**Comment by marcosgriselli** [comment]
Any updates @supermnemonic ?

**Comment by marcosgriselli** [comment]
Closed due to lack of consistency.
