### ISSUE TITLE
hangs on load if try to swipe

### ISSUE THREAD

**Issue by HaVaNa77** [marcosgriselli/SwipeableTabBarController#18]
Hi Marco, i'm using your fantastic swappable tabbar but i have a little problem, i've notice that sometimes when application loads it hangs if i make a swipe gesture, in my app i don't use swipe gesture, can you tell me how to disable it for all the viewcontrollers?
Maybe force disabling can stop the issue

**Comment by marcosgriselli** [comment]
So you just need the animation when tapping on the `UITabBarItem` right? So on your `SwipeableTabBarController` subclass just do `isSwipeEnabled = false` in your `viewDidLoad()`.

```
class TabBarController: SwipeableTabBarController {

    override func viewDidLoad() {
        super.viewDidLoad()
        isSwipeEnabled = false
    }
}
```

**Comment by HaVaNa77** [comment]
Thnx man, that fixed it!
