### ISSUE TITLE
Setting the subclass correctly

### ISSUE THREAD

**Issue by HackShitUp** [marcosgriselli/SwipeableTabBarController#22]
For some reason, the animations aren't working? I think this might have to do something with one of my view controllers having a navigation controller. I'll see if I can get more info on this issue because it was working perfectly fine before I tampered with one of the view controllers on storyboard.

**Comment by marcosgriselli** [comment]
Hi @HackShitUp, animations should work even when the `UIViewController` is inside a `UINavigationController` but only for the first `UIViewController` on the navigation stack. This way it doesn't interfere with 'swipe to go back' native UIKit functionality.

**Comment by HackShitUp** [comment]
@marcosgriselli yeah I assumed that a navigation controller has nothing to do with it. But for some reason, none of the animations work. The relationship view controllers recognize the pan gesture, it just doesn't perform the animation. Any suggestions on how to debug this?

**Comment by HackShitUp** [comment]
@marcosgriselli I also realized that the transition works in the beginning but only when you tap the UITabBar. In other words:
(1) The app launches.
(2) When you tap on any of the UITabBars, the transition performs with the animation.
(3) When you tap or swipe from the transitioned view controller, the transition executes, but the  animtion doesn't.

**Comment by marcosgriselli** [comment]
@HackShitUp It's working for me in the example app. Can you create a demo project with this error?

**Comment by HackShitUp** [comment]
@marcosgriselli sure, I'll see what I can do. I need to narrow down the scope of this project first, and that may take a while, but thank you!

**Comment by HackShitUp** [comment]
@marcosgriselli although I didn't include the scope of my own project using SwipeableTabBarController, I created a new one and was able to replicate it:

https://github.com/HackShitUp/SwipeIssue

**Comment by marcosgriselli** [comment]
@HackShitUp I just reviewed the project you were missing setting your `UITabBarController` class on the storyboard to `MasterUI`. 

That's also why any of the UI customization on the `Master UI` class wasn't working.

<img width="1181" alt="screen shot 2017-09-15 at 3 56 42 pm" src="https://user-images.githubusercontent.com/14804033/30498853-ab3bd88e-9a2e-11e7-8f71-1407bafb66be.png">

**Comment by HackShitUp** [comment]
@marcosgriselli I realized I submitted the project carelessly without setting the storyboard's class. BUT I did figure out what prevented the animations.

If the relationship view controllers conform to the UITabBarControllerDelegate like so:

``` swift
override func viewDidLoad() {
    super.viewDidLoad()
    
    navigationController?.tabBarController?.delegate = self
}

// MARK: - UITabBarControllerDelegate Method
func tabBarController(_ tabBarController: UITabBarController, didSelect viewController: UIViewController) {
// ...
}

```
