### ISSUE TITLE
I need to use left gesture on first tap but gesture not working

### ISSUE THREAD

**Issue by alkincakiralar1996** [marcosgriselli/SwipeableTabBarController#23]
let swipeRight = UISwipeGestureRecognizer(target: self, action: #selector(rightGesture))
        swipeRight.direction = UISwipeGestureRecognizerDirection.right
        self.view.addGestureRecognizer(swipeRight)

        setSwipeAnimation(type: SwipeAnimationType.push)
        setTabBarSwipe(enabled: true)

    func rightGesture() {
        print("gesture")
    }

its not working what should i do ?

**Comment by marcosgriselli** [comment]
What do you mean on first tap? You shouldn't be adding `UISwipeGestureRecognizer` for the animations to work.

**Comment by alkincakiralar1996** [comment]
your library is perfectly woking thank you but i just have one problem

in my first tap page of tap controller  i have table view

when i pull from top to bottom to reload datas , passing page to next or previous page.

if the finger's movement from top to bottom or bottom to top i have to cancel this action, it must be fetch the datas

the other tap pages are not tap controller page
they all are view controller page

**Comment by marcosgriselli** [comment]
I recommend you use `setDiagonalSwipe(enabled: true)` to avoid diagonal or up and downs swipes affect the tabBar animations.
