### ISSUE TITLE
Can you make the swipe smoother?

### ISSUE THREAD

**Issue by HackShitUp** [marcosgriselli/SwipeableTabBarController#29]
Sorry, this isn't a bug, but I think the UIPanGestureRecognizer could optimize performance when navigating between view controllers in the UITabBarController.

**Comment by marcosgriselli** [comment]
Well, there's not much going on on the SwipeInteractor. Are you getting performance issues when swiping?

**Comment by HackShitUp** [comment]
@marcosgriselli Sometimes, the app "blacks - out" on the camera if I swipe too fast or the view controllers freeze in their previous positions. But I figured it wasn't an issue pertaining to this project because I'm customizing the tabbar (I make the tabbar translucent and I apply a gradient background shadow to it) which may be causing it.

**Comment by HackShitUp** [comment]
It's quite hard to build a project such as this that "just works" when trying to modify what's given with UIKit.

**Comment by marcosgriselli** [comment]
@HackShitUp please check [1.0.10](https://github.com/marcosgriselli/SwipeableTabBarController/releases/tag/1.0.10) release. It handles the black screen situation.

**Comment by HackShitUp** [comment]
@marcosgriselli Thanks, but I've decided to forgo using SwipeableTabBarController for my application...
