### ISSUE TITLE
Issues mentioned as fixed in v1.0.10 still occurring in iOS 11.0

### ISSUE THREAD

**Issue by ghost** [marcosgriselli/SwipeableTabBarController#31]
Hello! I'd first like to thank the developers for maintaining this repo and making this great feature :)

I noticed that many issues such as the "black screen" and freezing after swiping quickly is still occurring for me. I'm running your test app called "SwipeableTabBarController_Example" that is in your repo, and my simulator is giving those issues still. Could it be that the simulator is in iOS 11.0? I am also on XCode 9.0, but I tried both deploying with Swift 3 and 4 and both are giving the issues.

**Comment by marcosgriselli** [comment]
Hi @Bobobocuz I will be fixing this issues soon. I've been really busy with work but I hope to find time soon to fix these problems.

**Comment by marcosgriselli** [comment]
@Bobobocuz Can you test it on a real device? I just tested on an iPhone X and the only way to get the Black Screen issue is by Swiping furiously and at the same time tap the tabBar item icons multiple times.

**Comment by marcosgriselli** [comment]
This issue will be managed by #32

**Comment by thealzgit** [comment]
I have just developed an App using your Library. It is so useful, but when i was testing it I found some bugs with that black Screen. If you click on a tab Bar Button while you are trying to swipe, you'll get a lil bug, sometimes you can go back, and sometimes if you continue clicking on the tabBarButtons, you get more space in black.
Thank you for sharing this library, your answer could be a great help.
