### ISSUE TITLE
Create without xib or storyboard?

### ISSUE THREAD

**Issue by sbrioux** [marcosgriselli/SwipeableTabBarController#33]
Is it not possible to create this class like the following:

```swift
let rootController = MySwipableTabBarController();
UIApplication.shared.keyWindow?.rootViewController = UINavigationController(rootViewController: rootController);
```

**Comment by marcosgriselli** [comment]
@sbrioux can you add a more detailed description? Are you getting an error/crash? an empty screen?

**Comment by sbrioux** [comment]
Currently you can't even compile because there is not init() constructor in the SwipeableTabBarController class.  Has to use the init(coder aDecoder: NSCoder) method.

The MySwipableTabBarController is basically:
```swift
import SwipeableTabBarController;

class MySwipeableTabBarController: SwipeableTabBarController {

    private var oneVC = OneViewController()
    private var twoVC = TwoViewController()
    private var threeVC = ThreeViewController()
    private var fourVC = FourViewController()

    override func viewDidLoad() {
        super.viewDidLoad()
        delegate = self;

        // Add the controllers to the tab bar
        oneVC.tabBarItem = UITabBarItem(title: "One", image: #imageLiteral(resourceName: "one"), tag: 0);
        twoVC.tabBarItem = UITabBarItem(title: "two", image: #imageLiteral(resourceName: "two"), tag: 1);
        threeVC.tabBarItem = UITabBarItem(title: "three", image: #imageLiteral(resourceName: "three"), tag: 2);
        fourVC.tabBarItem = UITabBarItem(title: "four", image: #imageLiteral(resourceName: "four"), tag: 3);
        let tabBarList = [oneVC, twoVC, threeVC, fourVC];
        viewControllers = tabBarList;    
}
```

However, currently you can't build because of the line
```swift
let rootController = MySwipeableTabBarController()
```
Get the error:
    Missing argument for parameter 'coder' in call

**Comment by marcosgriselli** [comment]
@sbrioux Good catch! I forgot to make the initializer public on `SwipeableTabBarController`. A fix has been deployed on [release 1.0.14](https://github.com/marcosgriselli/SwipeableTabBarController/releases/tag/1.0.14)

**Comment by sbrioux** [comment]
Not sure if it's a side effect or not but now trying to use any of the following methods crashes the application:

Inside the viewDidLoad:
```swift
setSwipeAnimation(type: SwipeAnimationType.sideBySide)
setDiagonalSwipe(enabled: true)
```

As well the swipe gestures don't seem to work until a tab is selected from the bottom.

**Comment by marcosgriselli** [comment]
Sorry for that @sbrioux I made a better fix and tested it :). There's a new release.
