### ISSUE TITLE
Add UIScreenEdgePanGestureRecognizer support

### ISSUE THREAD

**Issue by sbrioux** [marcosgriselli/SwipeableTabBarController#34]
I notice you use the pan gesture recognizer.  Any future plans to support an edge gesture recognizer?

**Comment by marcosgriselli** [comment]
Sounds useful, specially for screens that have horizontal scrolling content. I wasn't considering adding support for it but I might do it. I'll leave this as a low priority task unless it gets a few thumbs up.

**Comment by sbrioux** [comment]
Horizontal scrolling is exactly my reason for asking.

**Comment by Amnell** [comment]
Keep in mind the edge cases (no pun intended) when adding a EdgePan where it will interfer with UINavigationControllers and their native swipe to go back functionality. UX may suffer when panning between multiple tabs and suddenly navigation stacks begin to pop

**Comment by marcosgriselli** [comment]
@Amnell the current implementation only applies the gesture recognizer to the first `UIViewController` of a `UINavigationController` hierarchy. This might be modified but I feel that swiping from a pushed view controller to another view controller inside the `UITabBarController` doesn't follow the native UX.

On `selectedViewController` change: 
```swift 
swipeInteractor.wireTo(viewController: selectedController.firstController())
```

**Comment by ashald** [comment]
Do you think it can be an optional feature?

**Comment by marcosgriselli** [comment]
@Ashald the edge pan? Yeah, shouldn't be too complicated to support edge pans but I currently don't have the time to work on it.

**Comment by marcosgriselli** [comment]
This might get added on the `refactor` branch since it shouldn't be too troublesome to add it. Any help would be appreciated.
