### ISSUE TITLE
Swipe to mapView sometimes causes wrong index ?

### ISSUE THREAD

**Issue by MorganBerger** [marcosgriselli/SwipeableTabBarController#41]
Hi there,
I'm having a issue working with your pod. 

I got those 3 view controllers embed in a custom UITabBarController, child of SwipeableTabBarController : 
<img width="469" alt="screen shot 2018-05-21 at 11 18 22" src="https://user-images.githubusercontent.com/5556307/40300168-b7e54480-5ce8-11e8-98db-d7028a6905d6.png">

As you can see, my second controller contains a MKMapView.

Here's the problem: when my app opens, if I start scrolling quickly after the first view appears, the tab bar won't move at all when scrolled. I can only change tab by tapping the tab bar items. However when tapping the second tab then the first one again, my app will crash with : "Attempted to read an unowned reference but the object was already deallocated".
Showing this : 
<img width="400" alt="screen shot 2018-05-21 at 11 18 22" src="https://user-images.githubusercontent.com/5556307/40300510-bae8eae6-5ce9-11e8-828e-b29acef60553.png">

I found that setting `self.selectedIndex = 0` in the TabBarController viewDidLoad method fixes the issue. But when doing this, the scroll seems disabled until I first tap on a tab bar item. After this it works fine. 

I only saw that bug when adding a MKMapView though.

Thanks!

**Comment by marcosgriselli** [comment]
Can you try doing `selectedViewController = viewControllers?.first` instead? It's a strange issue, the ViewController content shouldn't affect others ability to swipe.

**Comment by MorganBerger** [comment]
Doesn't change anything sorry, the crash occurs in SwipeAnimation.swift line 73. I get a big fat SIGABRT.
Can you check this out?

**Comment by marcosgriselli** [comment]
Sure, is there any chance you create a repo with a small project where I can see the bug? Just so we test on the same code.

**Comment by MorganBerger** [comment]
You can find it at : https://github.com/MorganBerger/TrySwipeTabBarPod
Try spamming small swipes at launch, the bug should occur.
I run it on iPhone SE with iOS 11.3.1

**Comment by marcosgriselli** [comment]
@MorganBerger I just tried it out. This is a super strange bug. If you add `selectedViewController = viewControllers?.first` on `viewDidLoad` it will work if you use the app regularly. But if you spam small swipes at launch the swiping doesn't work. I'll look at it further.

**Comment by marcosgriselli** [comment]
@MorganBerger I just pushed v2.0 and I believe this issue should not happen anymore. Not sure if you still use the library. Otherwise, I'll close this issue.

**Comment by MorganBerger** [comment]
You can close the issue. Thanks !
