### ISSUE TITLE
Logo design proposal

### ISSUE THREAD

**Issue by Tobaloidee** [marcosgriselli/SwipeableTabBarController#42]
Good day Sir @marcosgriselli , I am Tobaloidee and i am a Graphics Designer. I want to contribute to your nice project if you will permit me, regarding a logo design which i am going to do as a gift for free. I'll wait for your approval before I start designing Sir. I've noticed that it doesn't have a logo yet so i thought of helping out. Thanks and best regards!

**Comment by marcosgriselli** [comment]
Hi @Tobaloidee, absolutely! This project could definitely use a nice logo, I really appreciate it :).

**Comment by Tobaloidee** [comment]
Thanks for allowing me Sir..will start the design and show you here asap..

**Comment by Tobaloidee** [comment]
Sir, here's my design based from the feature of the project which is "swipeable tabbar" 

favicon
![swipeable-01 - copy](https://user-images.githubusercontent.com/36028424/41480576-78db0874-7101-11e8-8767-3495c886791d.png)
logotypes
![swipeable-02 - copy](https://user-images.githubusercontent.com/36028424/41480580-7df7c32e-7101-11e8-8cd0-eef2a8280a55.png)

color options 

![swipeable-03 - copy](https://user-images.githubusercontent.com/36028424/41480635-a04abaf8-7101-11e8-9b1d-8ecf82388458.png)

let me know if you have some suggestions Sir so that i can edit.. :)

**Comment by marcosgriselli** [comment]
Sweet @Tobaloidee ! I really like it. I Feel the first logotype with Swipeable on the top and TabBarController on the bottom but with the same font and color fits better, otherwise it looks like the keyword is Swipeable and TabBarController is just a subtitle. 

I wonder if there's quality reduction here. Can you upload it to dropbox or drive and share the download link? I need the favIcon in 1024x1024 so I automatically generate them in all sizes necessary. That pink color looks good! 👍

**Comment by Tobaloidee** [comment]
Here Sir, pink version and adjusted logotypes...I can make a PR and upload the 1024x1024 SVG files for any scaling implementations if you like Sir.

![untitled-3](https://user-images.githubusercontent.com/36028424/41481825-fed5e60c-7105-11e8-9537-a608e70b43c6.png)

**Comment by marcosgriselli** [comment]
Can I get the app icon only in 1024x1024? So I add it to the demo app. You can create a PR with the banner as SVG and add it to the Readme. I try to follow this style with regards banner in the readme: 

<img width="1083" alt="screen shot 2018-06-15 at 14 57 49" src="https://user-images.githubusercontent.com/14804033/41482621-8b94ef16-70ac-11e8-8445-621598fc4e0d.png">

**Comment by Tobaloidee** [comment]
You can download the favicon 1024x1024 her Sir..https://drive.google.com/drive/folders/1RWT4gfUjfuaKINujYZcl1aMiVDmBKaOu

I'll make a PR now and upload the other files

**Comment by Tobaloidee** [comment]
created a PR #43 Sir, Thanks for accepting my proposal.. If you need any help regarding some modifications regarding logo in the future you can notify me. :) best regards!
