### ISSUE TITLE
Swipe animation not changing

### ISSUE THREAD

**Issue by darbysauter** [marcosgriselli/SwipeableTabBarController#44]
In my viewDidLoad I am setting both swipe and tap to overlap I believe this is even copied from the example. When I tap on the tab it does the overlap animation but swiping just does side by side.

```
class TabBarController: SwipeableTabBarController {
    override func viewDidLoad() {
        super.viewDidLoad()

        setSwipeAnimation(type: SwipeAnimationType.overlap)
        setTapAnimation(type: SwipeAnimationType.overlap)
        setDiagonalSwipe(enabled: true)
    }
}
```

I was also wondering if there was any built in way of hijacking the current animation as right now when you swipe once or tap, you cannot do another one until the animation is done. To me it just feels not clean, I would like to be able to re grab or swipe back midway through the animation, Or be able to tap another tab during the animation incase you tapped the wrong one. I will continue to look for a way that was implemented and if not I will look at modifying your code and if I find a way I will post here

**Comment by marcosgriselli** [comment]
Good call @mumphus, the swipe animation was not being changed correctly and always started with `.sideBySide`. 

With regards the other issue I need to implement interruptible transitions. I'll create a specific issue for that but it's not a high priority task for now.
