### ISSUE TITLE
Fails when setting selectedIndex

### ISSUE THREAD

**Issue by davidmichaelhogan** [marcosgriselli/SwipeableTabBarController#45]
Hi! 

I'm trying to set self.selectedIndex to the middle option of my menu so I can swipe either way to get to the other views. Whenever I add self.selectedIndex the swipe function just seems to no longer work...

Any ideas would be greatly appreciated !

**Comment by marcosgriselli** [comment]
Hi @cr-ks you need to update the `selectedViewController` property instead of the `selectedIndex` to trigger the gesture setup: 

```swift
selectedViewController = viewControllers?[1]
```

**Comment by tomsqrd** [comment]
Do you plan on resolving this bug in the future? Considering setting "selectedIndex" is the usual practice when manually switching to a tab of a tabBarController, this seems like a rather important issue (I just ran into it myself about 10 minutes ago and almost opened a new issue beforeI saw this thread).

**Comment by marcosgriselli** [comment]
@TomQDRS just created a new issue for this #46

**Comment by wdurkee** [comment]
Hi even when I use selectedViewController my app crashes.

I get this when I try to set as detailed in the example in the repository
<img width="605" alt="Screen Shot 2020-12-09 at 3 48 07 PM" src="https://user-images.githubusercontent.com/14866674/101706628-5f870680-3a3e-11eb-9a4f-0d04edd98001.png">

When I comment it out I get this warning
<img width="594" alt="Screen Shot 2020-12-09 at 3 50 23 PM" src="https://user-images.githubusercontent.com/14866674/101706658-73cb0380-3a3e-11eb-84a9-f50ad666f930.png">

Any clue to what might be going on?  (Also thanks for this library its very useful!)

**Comment by marcosgriselli** [comment]
@wdurkee it seems like you're getting an unrelated problem. The first screenshot mentions that the NIB is not loadable and the second one that you're passing an invalid attribute to the 'User Defined Runtime Attributes' inspector on Interface Builder. Can you share the code so I can point to a possible solution? `selectedViewController` and `selectedIndex` both should work programmatically as expected. You can try both properties on the example app.
