### ISSUE TITLE
didSelect delegate method not called when swipe achieved

### ISSUE THREAD

**Issue by OxyFlax** [marcosgriselli/SwipeableTabBarController#47]
When I click on the tab, 
`func tabBar(_ tabBar: UITabBar, didSelect item: UITabBarItem)`
 is called, but when I swipe, it's not.

**Comment by marcosgriselli** [comment]
@OxyFlax that method is from the `UITabBarDelegate`. I think its fine if it's not triggered by the `UITabBarController` custom transition as there was no interaction with the `UITabBar`. Please use `UITabBarControllerDelegate` `tabBarController(_ tabBarController: UITabBarController, didSelect viewController: UIViewController)` method. I just added a manual trigger on release [1.3.2](https://github.com/marcosgriselli/SwipeableTabBarController/releases/tag/1.3.2). You can check the usage on: https://github.com/marcosgriselli/SwipeableTabBarController/blob/1.3.2/Example/SwipeableTabBarController/TabBarController.swift#L30

**Comment by OxyFlax** [comment]
Thanks!
