### ISSUE TITLE
Disable Animation on Tab Bar Item press

### ISSUE THREAD

**Issue by pistacia** [marcosgriselli/SwipeableTabBarController#49]
Some users can sometimes find transition animation annoying when they navigate using the tabBarController. (when they press tab bar items)

Is there a way to disable animation on `tabBar(_ tabBar: UITabBar, didSelect item: UITabBarItem)` but enable it on both left and right swipe gesture?

**Comment by marcosgriselli** [comment]
Check release [1.3.1](https://github.com/marcosgriselli/SwipeableTabBarController/releases/tag/1.3.1). You can disable it anywhere. Check the app for an example on how to use it.
