### ISSUE TITLE
Using SwipeableTabBarController with inner UINavigationController having few children controllers

### ISSUE THREAD

**Issue by VitaliyR** [marcosgriselli/SwipeableTabBarController#51]
Hello!

In case of structure:

* SwipeableViewController
  * UINavigationController
    * UIViewController
      * UIViewController - let's call it inner controller (with back button in the navigationbar) 

So, when I'm seeing this inner controller, I can't swipe between SwipeableViewController children controllers. I can swipe to make 'back' action from the edge of the screen and that's it. 

How can I solve this one? I think it is common action which is not described in README

Thanks.

**Comment by marcosgriselli** [comment]
Hi @VitaliyR, currently the swipe gesture is only added to the `UINavigationController`'s `rootViewController` to avoid interfering with the 'swipe to go back functionality'. I briefly discussed the reasons behind this approach here: https://github.com/marcosgriselli/SwipeableTabBarController/issues/34#issuecomment-385273931

**Comment by VitaliyR** [comment]
@marcosgriselli can't these two gestures work together? And how to override that functionality if it is under fileprivate?

**Comment by VitaliyR** [comment]
@marcosgriselli as far as I've tested - it works pretty well - back gesture is working just near screen edge and not allowing switching tabs, while if you swipe few pixels after the edge - swipeInteractor catches it correctly

**Comment by marcosgriselli** [comment]
That's great. I don't recall the exact reason for this decision but any horizontal swipe brought issues on the first few versions. Let me check if we can make it an opt-in feature.

**Comment by marcosgriselli** [comment]
Hey, this feature will be added on the next release. I'm working on the `refactor` branch.

**Comment by marcosgriselli** [comment]
@VitaliyR I pushed v2.0 today. This should be working fine.

**Comment by marcosgriselli** [comment]
I'll close this issue for now.
