### ISSUE TITLE
isSwipeEnabled causing crashes 

### ISSUE THREAD

**Issue by RobyHTS** [marcosgriselli/SwipeableTabBarController#55]
isSwipeEnabled = false

App getting crashed When I use this in your latest update. Kindly check and update me ASAP. 
Urgent.. 
Thanks in advance..

**Comment by marcosgriselli** [comment]
Hey @RobyHTS, when are you calling `isSwipeEnabled`? I'm trying it out on the demo project and everything works fine.

**Comment by RobyHTS** [comment]
setTabBarSwipe(enabled: false)

@marcosgriselli am using it on my tabviewcontroller also in my uiviewcotroller. But it could not working. Still i can swipe my tabviewcontroller.

Actually what I need is, I have tab with 3 viewcontroller. In my first tab I have range slider.. When I scroll the slider means, ViewController also moving. This is my problem. I need to restrict the swipe in my first tab ViewController.

**Comment by blinkuz** [comment]
@RobyHTS I just did some tests on one of my apps and the setTabBarSwipe (enabled: true) works perfectly on a ViewController.

**Comment by marcosgriselli** [comment]
Any update on this @RobyHTS ?
