### ISSUE TITLE
isSwipeEnabled is not working at first view load.

### ISSUE THREAD

**Issue by AalokParikh** [marcosgriselli/SwipeableTabBarController#56]
On `viewDidAppear()` method I try to call the `self.setTabBarSwipe(enabled: false)`. But each time the horizontal swipe changes the tab of the tab bar view controller.
And when I again come to the same view by swiping back, the code works correctly and the horizontal swipe will not change the tab. 

Why?

What I'm doing wrong, I don't get it.
Please help me with this issue.

**Comment by marcosgriselli** [comment]
@AalokParikh You're trying to set `setTabBarSwipe(enabled: false)` on you view controller that's the first view controller selected by the TabBarController, right?

**Comment by AalokParikh** [comment]
Yes, I do.
Also, I tried to set it in other view controllers. Like, when I pushed a new view controller.

If you want I will post my code here for your reference

**Comment by AalokParikh** [comment]
I found out the issue with it. The other third-party library is causing the issue. Have commented the code for that part of the library and now all working fine now.
