### ISSUE TITLE
handlePan pans when you are going up/left or up/right or down/right or down/left

### ISSUE THREAD

**Issue by Hsanka6** [marcosgriselli/SwipeableTabBarController#6]
One of the problems I ran into while I was using this library was that the pan view was scrolling left or right if I was going diagonally. This was VERY annoying. I was able to fix this (for the most part) with this code. Basically, I detect if the user is scrolling up or down, and if they are, we don't use the pan handler, we simply return. 

```swift 3.0
func handlePan(_ recognizer: UIPanGestureRecognizer) {

      ....

       if ( recognizer.translation(in: recognizer.view?.superview).y > 0){
            //up
            return
        }
        if ( recognizer.translation(in: recognizer.view?.superview).y < 0){
           // down
           return
        }

      ....
}
```

**Comment by marcosgriselli** [comment]
I'll take it into account, the tricky part is that what happens when you are swipping left/right but it's not a perfect horizontal line? I'll add some margins for it.

**Comment by Hsanka6** [comment]
I was trying to figure that out but it'll take me a while since I'm not familiar with your code completely but the code above helped a lot with like a diagonal swipe. You had it at > .5 and then it switches the page but that doesn't work perfectly. If you fix it you should update your pod!
