### ISSUE TITLE
Very quick swipes cause app to freeze

### ISSUE THREAD

**Issue by krgoodnews** [marcosgriselli/SwipeableTabBarController#62]
Hi, marcosgriselli.

This is very similar to Issue #52 
This situation does not appear in version 1.4, but appear in version 2.0.
I guess there was a problem with the refactoring process.
Please resolve it.

Thank you.

**Comment by marcosgriselli** [comment]
Again? What's your setup? I was never able to replicate that issue again on v2.0

**Comment by krgoodnews** [comment]
I had a manual installation.
I tried viewController.loadViewIfNeeded() when I loaded the tab bar and it was fixed.
Thank you. marcosgriselli.

**Comment by deweydbb** [comment]
I am still experiencing this issue in version 2.1. Can you elaborate on what you mean by viewController.loadViewIfNeeded()? Here is the test project where I am experiencing the issue: [https://github.com/deweydbb/TabBarTest](url)

**Comment by CameraPost** [comment]
thanks @deweydbb , and @krgoodnews -- I'm also interested in hearing about 'viewController.loadViewIfNeeded()' and how that resolves. Swiping among tabs results in freezing and wondering if there is some way to cause to stop happening. I have 5 tabs in my app. Thanks.
