### ISSUE TITLE
offer new feature: Enable Cycling Tab Bar

### ISSUE THREAD

**Issue by krgoodnews** [marcosgriselli/SwipeableTabBarController#64]
Hi, marcosgriselli.

If panning right at first view controller, transition to the last view controller.
And panning left at last view controller, transition to the first view controller.

What do you think about?

Thank you.

**Comment by marcosgriselli** [comment]
I like the new feature. Thanks for the PR. I added a few comments. Please try to use the Issue template the next time.

**Comment by marcosgriselli** [comment]
Added on #63
