### ISSUE TITLE
Black screen when tapping 2 tabs simultaneously 

### ISSUE THREAD

**Issue by natinas** [marcosgriselli/SwipeableTabBarController#67]
i open the exemple project, i click on 2 tab bar item in the same time and i have a black screen.

i see that you've already resolved this bug but i've it again.

your help is welcome :D

**Comment by marcosgriselli** [comment]
Hi @natinas can you provide a sample project? I noticed that this issue depends on what actions you're performing on the view controller you're transitioning to for the first time. My guess is that the main thread is trying to load the view controller for the first time and the transition tries to finish before this is done.

**Comment by natinas** [comment]
hello @marcosgriselli , i take the project example in your repo (https://github.com/marcosgriselli/SwipeableTabBarController/tree/master/Example).

to reproduce the bug, you need to click on 2 or more tab bar item simultaneously.
you have this result :
![UNADJUSTEDNONRAW_thumb_b](https://user-images.githubusercontent.com/19586905/58000358-d9604380-7ad8-11e9-8d53-162f861db74c.jpg)

**Comment by marcosgriselli** [comment]
@natinas I added a PR with the fix for this issue. Do you want to take a look at the branch and see if it works as expected?

**Comment by natinas** [comment]
@marcosgriselli 
i test your branch (fix-double-transition-bug) and the bug seems to be removing :) 
thx for your help.

**Comment by danielbenedykt** [comment]
Hi,  

I still see this issue in 2.1.1
Basically is not clicking on 2 tabs,  but sometimes when I run from xcode, I see a blank screen on 1 of the tabs. 
I have to clean the project and run it again to make it work.
