### ISSUE TITLE
MapView in Controller

### ISSUE THREAD

**Issue by sirvon** [marcosgriselli/SwipeableTabBarController#7]
What happens with one of the tabs contain a MapView or a swipable tableview cell?

How can we ensure that swiping to next VC will work as intended.

thanks!

**Comment by marcosgriselli** [comment]
Let's assume you have a swipeable cell, when should it swipe the cell and when should it swipe the tab bar?

**Comment by marcosgriselli** [comment]
@sirvon

**Comment by marcosgriselli** [comment]
Added support to disable interactive swipe when needed a0a9e8a

**Comment by sirvon** [comment]
Sorry, been away from code for a second...

So, if there's a map in one of the tab controllers
do 
```
setTabBarSwipe(enabled: false)
```
so pretty much swipe functionality is gone when mapview is on screen....

In a perfect world, when a user swipes from the edges of screen, then move to appropriate controller.

**Comment by marcosgriselli** [comment]
> In a perfect world, when a user swipes from the edges of screen, then move to appropriate controller.

That's a good idea, I'll keep it mind for future versions to support maps, horizontal scrollViews and swipeble cells.
