### ISSUE TITLE
func tabBarController not called on swipe

### ISSUE THREAD

**Issue by jfoucher** [marcosgriselli/SwipeableTabBarController#71]
## Expected Behavior
I expect the `tabBarController didSelect` method to be called when I change tabs with a swipe.
It it properly called when I tap on the tabs themselves

## Current Behavior
The `tabController didSelect` method is not called on swipe

## Possible Solution
No, sorry :/

## Steps to Reproduce (for bugs)
1. Download this repository
2. in the Example folder open the workspace in xcode
3. Add `print("changed")` in TabBarController.swift below line 37
4. Run in simulator
5. Something is printed when tapping the tabs
6. Nothing is printed when swiping

## Environment

* SwipeableTabBarController version: 2.1.1
* Device and OS running tests: Xcode simulator
* Demo project link: https://github.com/marcosgriselli/SwipeableTabBarController/tree/master/Example

**Comment by marcosgriselli** [comment]
Hey @jfoucher thanks for reporting this. Selection works in a strange manner. I recommend you observe the `selectedIndex` property and react to changes. You can do it this way: 

```swift 

    private var observation: NSKeyValueObservation?

    observation = self.observe(\.selectedIndex, changeHandler: { [weak self] _,  _ in
        self?.selectedIndexWasUpdated()
    })
    
    private func selectedIndexWasUpdated() {
        /// code
    }
```

**Comment by jfoucher** [comment]
Ok, thanks for the workaround @marcosgriselli
