### ISSUE TITLE
Any possibility to change animation duration when tapping between tabs?

### ISSUE THREAD

**Issue by stepan23021** [marcosgriselli/SwipeableTabBarController#72]
Hello, thank you for your awesome SwipeableTabBarController. I'm just wondering if there is a possibility to change animation duration when tapping on tabs, making it a little faster? Thanks in advance.

**Comment by marcosgriselli** [comment]
Hey @stepan23021, the `animationDuration` property on `SwipeTransitionAnimator` is `private` so there's no way to set it. It shouldn't be difficult to expose it and add a function that sets this duration on `SwipeableTabBarController`. Wanna give it a go on a PR? I can help out.
