### ISSUE TITLE
App freezes when first use 

### ISSUE THREAD

**Issue by AlbertoMalavasi** [marcosgriselli/SwipeableTabBarController#74]
## Expected Behavior
First time I open the app and I swipe right, it should work as expected

## Actual Behavior
App freezes, after a while when pressing other buttons it works again and keeps working as expected.

- Some errors and updating to swift 5 required.

## Steps to Reproduce the Problem
Install it and add it to tab bar

## Specifications

  - Version:
  - Platform: iOS 13.1
  - Subsystem:

**Comment by marcosgriselli** [comment]
Moving this to #52 which has more participants
