### ISSUE TITLE
setting defaultIndex breaks Swipe

### ISSUE THREAD

**Issue by makthrow** [marcosgriselli/SwipeableTabBarController#8]
If I subclass SwipeableTabBarController to add a defaultIndex for a different tab,
the default index works correctly to take me to the second tab (tab 1) but it breaks swipe.

That is, until I go to another tab by clicking on the tab icon. Then, swipe starts working again.

Any idea why this is?

     `import SwipeableTabBarController

    class SwipeableTabBarControllerSub: SwipeableTabBarController {
    
    @IBInspectable var defaultIndex: Int = 1
    
    override func viewDidLoad() {
        super.viewDidLoad()
        selectedIndex = defaultIndex
    }
    
}`

**Comment by makthrow** [comment]
in another class, when I use this command:

tabBarController?.selectedIndex = 1

the swipe is also broken until I manually click a tab bar icon.

so I think it's the programatically selecting an index that breaks swipe

**Comment by makthrow** [comment]
ok after reading your example I think I fixed programatically change tabs with:
` tabBarController?.selectedViewController = tabBarController?.viewControllers?[1]`

and fixed the default selected tab code with

    override func viewDidLoad() {
        super.viewDidLoad()
        selectedViewController = viewControllers?[1]
    }

**Comment by marcosgriselli** [comment]
Yes I might need to add something to clear that out as general rule of thumb with `UITabBarController` is to change controllers with `selectedIndex` but this doesn't work with viewController observer to enable the swipe. I'll think of a solution to make it straight forward.
