### ISSUE TITLE
Set minimum or maximum number of touches for recognizer

### ISSUE THREAD

**Issue by kyuuuyki** [marcosgriselli/SwipeableTabBarController#80]
## Expected Behavior

If number of touches set to 3, it should only able to swipe when I use 3 fingers.

## Current Behavior

Cannot using specific number of touches to swipe.

## Environment

* SwipeableTabBarController version: 2.1.1
* Device and OS running tests: iPad Mini 4, iOS 13.3

**Comment by marcosgriselli** [comment]
@kyuuuyki this is a straightforward feature, would you like to send a PR? I can help out with it.

**Comment by kyuuuyki** [comment]
I still can't figure out how to swipe (with more that 1 finger) on UICollectionView. 

Since that issue (#81) is related to this issue, 
I think it will be best if you commit both on your PR.

However, thanks for your pod. great work!
