### ISSUE TITLE
Swipe on UICollectionView using more than 1 finger

### ISSUE THREAD

**Issue by kyuuuyki** [marcosgriselli/SwipeableTabBarController#81]
## Expected Behavior
If I set minimum number of touches to 3, It should swipe to next tab even if i'm swiping on UICollectionView

## Current Behavior
Cannot swipe to next tab on UICollectionView

## Environment

* SwipeableTabBarController version: 2.1.1
* Device and OS running tests: iPad Mini 4, iOS 13.3

**Comment by marcosgriselli** [comment]
Closing this since it is the same feature request as #80.
