### ISSUE TITLE
Swipe to ViewController programmatically

### ISSUE THREAD

**Issue by LoopingLouieX** [marcosgriselli/SwipeableTabBarController#85]
Hi,
sorry for this stupid question but I've tried a lot of things right now but don't come across a solution.
I've managed to set up everything and it's working really great.
But now I want to swipe to specific ViewControllers programmatically from a button as example.
How can I get this working ?

Thanks!

**Comment by marcosgriselli** [comment]
Hi @LoopingLouieX. You just need to change the UITabBarController's `selectedIndex` value in the function that's called when the button is tapped. 

If it's called from one of the view controllers contained in the UITabBarController you'll have to do this:
```swift 
tabBarController?.selectedIndex = <yourNewIndex>
```
