### ISSUE TITLE
how can i stop swipe control for specific viewcontroller

### ISSUE THREAD

**Issue by arslan111222** [marcosgriselli/SwipeableTabBarController#87]
Your issue may already be reported!
Please search on the [issue track](https://github.com/marcosgriselli/SwipeableTabBarController/issues?utf8=✓&q=) before creating one.

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Environment

* SwipeableTabBarController version:
* Device and OS running tests:
* Demo project link:

**Comment by arslan111222** [comment]
i am working on chat as i move to chat box i dont need to swipe between controller until or unless i pop my chat box is there any possibility to stop swipe at that point.

**Comment by marcosgriselli** [comment]
@arslan111222 you'll need to call `setTabBarSwipe(enabled: false)` from the ViewController that you don't want to have swipe enabled. 

You can do this in `viewDidAppear` and re-enable it on `viewDidDisappear`.
