### ISSUE TITLE
Disable Swipe when pressing a button

### ISSUE THREAD

**Issue by makthrow** [marcosgriselli/SwipeableTabBarController#9]
Is there a way to disable swipe temporarily?

For example, when I'm holding down a record button on a camera, i don't want to let the user swipe tabs. Instagram has this for example.

**Comment by makthrow** [comment]
maybe add another condition  and variable,
    var TempDisableSwiped = false

private func shouldSuspendInteraction 
in SwipeInteractor class

eg.
if !TempDisableSwipe {
   return true
}

then in SwipeableTabBarController class:

open func setTemporaryDisableSwipe(enabled: Bool) {
    swipeInteractor.TempDisabledSwiped = enabled
}

then in any class i can use
        tabBarController?.setTemporaryDisableSwipe = true

and
        tabBarController?.setTemporaryDisableSwipe = false

**Comment by marcosgriselli** [comment]
Good point! I was thinking about adding something like excluded indexes, but this makes sense too, I'll set a milestone for this.

**Comment by marcosgriselli** [comment]
Forgot the commit message. Added support to disable the interactor at will a0a9e8a

**Comment by makthrow** [comment]
I'm not sure if I'm using this right.
When I call the function it doesn't disable the swipe.

`        tabBarController?.setTabBarSwipe(enabled: false)
`

I've tried this in viewDidLoad and upon a function a call.

edit: nvm, i realized now the ViewController is supposed to call it.
