### ISSUE TITLE
Is disabling tap animation not supported anymore?

### ISSUE THREAD

**Issue by wasp898** [marcosgriselli/SwipeableTabBarController#90]
I haven't found a way to disable the animation when tapping on a tab. But several issues and commits indicate that this was possible before.
Even the example app features this code (which is now commented) out:

`//tapAnimatedTransitioning = nil`

But `tapAnimatedTransitioning` is a get-only property.

Is there another way to achieve this now?

**Comment by wasp898** [comment]
I guess setting `animationDuration` to 0.0 does the job. The example should be updated. I could do that myself I guess.
I'm closing this issue for now.
Anyway, I did find a bug though. In my app I have other gestures which somehow cause the `currentAnimatedTransitioningType` to be of type Swipe instead of Tap type. After that, when I tap I still see the animation of default duration.
Will try to propose a solution.

**Comment by JMCPH** [comment]
Did you find to manage a clean fix for this?

**Comment by wasp898** [comment]
> Did you find to manage a clean fix for this?

I did actually. I’ll push a PR asap.
