### ISSUE TITLE
Problem with iPad in split screen

### ISSUE THREAD

**Issue by wasp898** [marcosgriselli/SwipeableTabBarController#98]
I have adopted this amazing solution in my app since I think July. I forked the project so that I could try to fix the [black-screen-issue](https://github.com/marcosgriselli/SwipeableTabBarController/issues/52) (and actually never got to it in the end 😅).

Anyways, only now I noticed a big issue that affects iPads in split screen (or with the app in floating mode), which is that the swipe transitions are computed based on the size of the device, and not the size of the view. This leads to transitions showing a huge amount of black nothing between two consecutive app screens.

My solution was straightforward and you can find it in this [commit](https://github.com/wasp898/SwipeableTabBarController/commit/fac61406daa84c3f9d693a2f69df95ab3d9b70be).
There may be better solutions to take the current view width, that's why I'm not making a PR yet. The solution works fine for my app as far as I can tell though.

**Comment by marcosgriselli** [comment]
@wasp898 I think that solution is perfect, maybe I'd use the `from` view since it is the one where the gesture takes place. Would you send a PR with the changes?
